generateSqlString = () => {
  const usernames = [
    "1 Up",
    "1/2 Shelly",
    "101 Darwin",
    "11 Scent",
    "20 Story Satan",
    "24 Carrot Seven",
    "24 Hour Jesus",
    "2lil2late",
    "33Ease",
    "3Demon",
    "409",
    "59design",
    "60 Grit",
    "64 Megs of Ryan",
    "69 Scoops",
    "70 Umpa",
    "8Baldwin",
    "8Maha",
    "A Baby Maybe",
    "A!",
    "Abba Dash Sherry",
    "Abby Joseph Cohen",
    "Abundance Grand",
    "Acacian Spring",
    "Ace King 47",
    "Aces Fewl",
    "Aces UPp",
    "Acrobatty",
    "AcroBetty",
    "Acrodance",
    "Acronymaniac",
    "Acronymph",
    "Acronympho",
    "Acronymrod",
    "Adornica",
    "Aecium",
    "Aesthetic Bug",
    "AK So Ted",
    "Al Fresco",
    "Al Fresco’s",
    "Al Indigo",
    "Alanonymous",
    "All Indigo",
    "Alpha Moyle",
    "Amanda Marigold",
    "Angry Tank Swan",
    "Angryman",
    "Apathesis",
    "Appy Planet",
    "Arena Panza",
    "Argggggghhhhhhh",
    "Aroma Borealis",
    "Aromantic",
    "Aromastotle",
    "Artego",
    "Articular Matters",
    "Atilla Mockingbird",
    "B Cool 2 School",
    "B8nW8",
    "Baba Baba",
    "Baba Blongata",
    "Baba Rum",
    "Babble Belt",
    "Babblegate",
    "Babbling Brooklyn",
    "Baby Jail",
    "Bacon Bean",
    "Bad Glands",
    "Bad Rabbit",
    "Bad Vicky",
    "Baffledil",
    "Bait Bait Bait",
    "Bait’n Chase",
    "Bali Who",
    "Ball Lightning",
    "Balmy Steve",
    "Bambi Planet",
    "Bamboo Gnu",
    "Bamboolong",
    "Bang’aBone",
    "Banjo Pancake",
    "Bar Flyz",
    "BB Lutz",
    "Beanie Boyd",
    "Bear Trope",
    "Beauty Call",
    "Bee Salt",
    "Bee Saw",
    "Beef Sorbet",
    "Beer in Mind",
    "Before Coffee",
    "Beluga",
    "Beluga Bandit",
    "Ben tHeir",
    "Binarium",
    "Bitch Goddess",
    "Bite Sighs",
    "Bitter Plaid",
    "Bitterbug",
    "Blando",
    "Bleendot",
    "Bocca Bot",
    "Boilcat",
    "Booty Base",
    "Born to Scrum",
    "Brain Brand",
    "Brain Bunny",
    "Brain Butter",
    "Brain Carney",
    "Brain Crust",
    "Brain Mantis",
    "Brain Marrow",
    "Brain Muffin",
    "Brainclip",
    "Brainquil",
    "BrainWire",
    "Bran Dandy",
    "Brass Tactics",
    "Bravomissimo",
    "Broadway Baggins",
    "Broadway Chez",
    "Broadway Czar",
    "Broadway Dorian",
    "Broadway Tum Tum",
    "Budapest Priest",
    "Buddha Bait",
    "Buddha Belly",
    "Buddha Belt",
    "Buddha Bitch",
    "Buddha Bite",
    "Buddha Hatchet",
    "Buddha Loops",
    "Buddha My",
    "Buddha Pests",
    "Buddha Pets",
    "Buddhist Pest",
    "Buddy Ebsen Salt",
    "Buddy Hatchet",
    "Bull Throttle",
    "Buzzopia",
    "Cabañitis",
    "Cabbage Wars",
    "Calamari Cream",
    "Campxotica",
    "Canadiaunt",
    "Candy Ask",
    "Cap Happy",
    "Captain Bamboo",
    "Captain Curmudgeon",
    "Casuwalt",
    "Casuwalter",
    "Center Sanchica",
    "Chapter Elvis",
    "cHeCk iT oUT",
    "Cheek",
    "CheekyGeeky",
    "Cheese Panic",
    "Cheetah Chat",
    "Cheeze Pleeze",
    "Chenon So So",
    "Cherry Potter",
    "Chez Barbie",
    "Chez Castaway",
    "Chez Cheese",
    "Chez Kicks",
    "Chez Maggie",
    "Chez Moi",
    "Chez Naïveté",
    "Chez Too",
    "Chez Toupee",
    "Chibi",
    "Chicken Karma",
    "Chief Saskitune",
    "Chigger Pops",
    "Choco Lulu",
    "Ciàobama",
    "Clever Leather",
    "Click Fraud McGraw",
    "Closet Palace",
    "Cobalt Lightening",
    "Cobean",
    "Cocoa Clasp",
    "Coma Tostada",
    "Copabull",
    "Corn Dog Social",
    "Corn Doggery",
    "Could Be Worse",
    "Cow toOwn",
    "Cow2own",
    "Craveman",
    "Crotch Bacon",
    "Crotch Clover",
    "Crotch Custard",
    "Crotch Fire",
    "Crotch Jockey",
    "Crotch Opera",
    "Crotchwalk",
    "Crush Station",
    "Crustacean Prince",
    "Cubicide",
    "Cycle Suave",
    "Cyclodrone",
    "Cyclone",
    "Cyclovista",
    "Cyn DroNe",
    "Cyrene",
    "D. E. Light",
    "D.E. Lightful",
    "Dacron",
    "Dacron Dave",
    "Dada Dwiddle",
    "Daddy Knew",
    "Daffodildo",
    "Dag Nabbit",
    "Dahmer Pass",
    "Dairy Air",
    "Dairy Anne",
    "Damagansett",
    "Dan of the Dead",
    "Dan Steely",
    "Dancerity",
    "Dandit",
    "Dandy Layne",
    "Dare Care",
    "Darls",
    "Darwendy",
    "Darwin 911",
    "Darwin Again",
    "Darwin Sum",
    "Dar-Win-Again",
    "Darwinium",
    "Darwinter",
    "Deep C",
    "Deucebag",
    "Deucebra",
    "Deviltoe",
    "Deviltrope",
    "Digging Jane",
    "DigiAce",
    "Digicide",
    "Digicyde",
    "Digifad",
    "DigiGate",
    "Digimirror",
    "DigiPrawn",
    "Digiquarius",
    "Digit Man",
    "Digital Hygenist",
    "Digital Jones",
    "Digme",
    "Dis Taunt",
    "Divinitease",
    "Doc Hollandaise",
    "Doc Mantra",
    "Doc Virile",
    "Doctor Kudu",
    "Doctor Misely",
    "Doctor Sloth",
    "Donkey Shine",
    "Dote",
    "Downward Facing God",
    "Dr. Evil",
    "Dr. Grout",
    "Dr. Loop",
    "Dr. Mantra",
    "Dr. No",
    "Dr. Pan Ash",
    "Dr. Rumi",
    "Drama Mine",
    "Drama Trama",
    "Dramamine for Queeny",
    "Dramantra",
    "Dramatic Action",
    "dROP IN sOMEtImE",
    "Dusty Rainbow",
    "Dutchess Dutchass",
    "Dwealth",
    "e Me Up!",
    "E. Vixen",
    "Ear Blind",
    "Ear Corn",
    "Ear Pudding",
    "Ear Reverend",
    "EC Rises",
    "Elemaunt",
    "Email Cheese",
    "eMantic",
    "eMantis",
    "Emboldened",
    "eMealy",
    "Emergent",
    "Emmy Gump",
    "Emo Pigeon",
    "Emoltra",
    "Emotion Detector",
    "Empirica",
    "Everybody Zits",
    "Fabric Police",
    "Face Candy",
    "Fanatastic",
    "Father Earth",
    "Father Pickle",
    "Fear Tumbler",
    "Feather Lace",
    "Finsta Guana",
    "Firefly Friends",
    "Firenze",
    "First Snow",
    "Fish B8",
    "Fix n’ Vix",
    "Fixin’ Vixen",
    "Fix’t",
    "Flambo",
    "Fleshter",
    "Flip Ant",
    "Flop Star",
    "Flora Fiona",
    "Flush drAWE",
    "Flush Drawn",
    "Flush Eating Disease",
    "Flushter",
    "For-Moolah",
    "Freudian Slipper",
    "Fully Half Empty",
    "Gal Van Nuys",
    "GalaKala",
    "Galápaghost",
    "Gamboil",
    "Game Choy",
    "Game Face Jesus",
    "Gear God",
    "GeekBug",
    "Gems for Jesus",
    "Get Ovet It",
    "Gig Digit",
    "Ginger Snapping",
    "Girl Food",
    "Girl Pool",
    "Girltawk",
    "Glace Lass",
    "Glasnost",
    "Gleamer",
    "Globoil",
    "Glow Wonder",
    "Glucktor",
    "Gnoman",
    "Gnome Clone",
    "Googoyle",
    "Grainspot",
    "Greenclick",
    "Greenclicks",
    "Grill to Chill",
    "Grizzled Heights",
    "Guest Host Virus",
    "Guru Chew",
    "Guru Clue",
    "Guru Crew",
    "Guru Cricket",
    "Guru Hopper",
    "Guru Screw",
    "Guru Smile",
    "Guru Static",
    "Guru Sum",
    "Guru To Go",
    "Guru Too",
    "Guru Twine",
    "Gurucentric",
    "Guruphobic",
    "Guru-to-do",
    "Gwenevere Experience",
    "Haiku Harry",
    "Hair Looms",
    "Hair of the Doug",
    "Halcyon Arms",
    "Hambone Martian",
    "Happy Snout",
    "Hardy-har-har-able",
    "Harpo Marxism",
    "Harry Kerry",
    "Hawt Nawt",
    "Head Cheese Head",
    "Headcheese, LTD",
    "Hear 24",
    "Hell Lodi Kitty",
    "Herb Ruts",
    "Hercules Jerky",
    "Here 24",
    "Here Comes Me",
    "Here’s the Beef",
    "Hermes Spermes",
    "Herpulon",
    "hipYouth",
    "Historia Fonz",
    "Hobo Zo",
    "Hog Oscar",
    "Hoodie",
    "Hot Air Baboon",
    "Hot Box",
    "Hot Dogma",
    "Hot Duchess",
    "Hot Fauxtato",
    "Hot Kafka!",
    "Hot Magma!",
    "Hot Poddy",
    "Hot Schenectady",
    "Hot Trotsky",
    "Hot Vinyl",
    "HotBelly",
    "Hue Bris",
    "Hue’s Bris",
    "Humburger",
    "Hunt and Garter",
    "Igoraphobia",
    "Illumity",
    "Illustria 59",
    "Illustrioso",
    "Illustrious Oh",
    "Imperative",
    "Inducing Introducing",
    "Inhabitaunt",
    "Inhale Satan",
    "Ithacan Do",
    "Jabrappin",
    "Jack Addict",
    "Jack Itch",
    "Jack London Calling",
    "Jack Swayed",
    "Jack the River",
    "Jacket Straight",
    "Jackie Diamonds",
    "Jackscrew",
    "jaiL b8",
    "Jalapeño Fireball",
    "Jam Chops",
    "Jamnation",
    "Janet Planet",
    "Janky Bull",
    "Jay Crude",
    "Jay Krewd",
    "Jaynomics",
    "Jello Abuse",
    "Jello Tangent",
    "Jelly Baby Red",
    "Jelly Finch",
    "Jelly Sofas",
    "Jellybird",
    "JellyBone",
    "JellyEight",
    "Jellyfish",
    "Jellyfish Java",
    "Jetsam",
    "Jetsilk",
    "Jimbies",
    "Joe Cuzzi",
    "Jumpstack",
    "Keeper’s Promise",
    "Kimono Open",
    "King Bling",
    "King Chard",
    "King Conundrum",
    "King of Gnomes",
    "King Pong",
    "King Wasabi",
    "Kitch Kids",
    "Kobeen There",
    "La Canada Cutter",
    "La Concuna",
    "La Liz",
    "La Loopy",
    "LA Mischief",
    "Lady Plaid",
    "Lady Playd",
    "Lambastica",
    "Landscapel",
    "Largemount",
    "Latté Vomitté",
    "Lauralight",
    "Le Petit Chef",
    "League Swamp",
    "Leather Rip",
    "Letpro",
    "Lettuce Prey",
    "Li Li Chiq",
    "Lillytrope",
    "LimLim",
    "Local Focal",
    "Local Yokel",
    "Lolly Chelsea",
    "Lord Bone",
    "Lord Chuby Cheeks",
    "Lord Debit Card",
    "Lord Gunneysack",
    "Lord Hatchback",
    "Lord Martini",
    "Lord of the Flighs",
    "loRd Of tHe fLYz",
    "Lord on the Rocks",
    "Lord Sassybax",
    "Lou Cid",
    "Louvre Shack",
    "Love Bomb",
    "Love Digit",
    "Lovebox",
    "Lovebox Hotel",
    "Low Bald",
    "Low Balled",
    "Lowly Squat",
    "Ma Cranky",
    "Mach Epoch",
    "Macho Miso",
    "Macro Monk",
    "Mad About Cows",
    "Mad Grahams",
    "Mad Gravity",
    "Madam Curry",
    "Maggoteer",
    "Magic Happens",
    "Magnemo",
    "Maid of Horror",
    "Mail Freud",
    "Mallard Air",
    "Man Dingo",
    "Man Hole",
    "Man Swatter",
    "Manager Man",
    "Manatea",
    "Mando",
    "Mandrake",
    "Mangelica",
    "Manglo",
    "Mango Mango",
    "Maniacal Miss",
    "Manic Deprecedent",
    "Mannecantor",
    "Mannequin Depression",
    "Mannequin Mayhem",
    "Mannequin Mime",
    "Mannequin Mogul",
    "Manson",
    "Manster Mosh",
    "Mantis Milk",
    "Mantrix",
    "Mantro",
    "Marketoid",
    "Marquis de Sob",
    "Math Compressor",
    "Mayhem Line",
    "Meat Bomb",
    "Memberbember",
    "Memeosphere",
    "Merger Mystery",
    "Mia My",
    "Mirror Mirror",
    "Mod Pod",
    "Mongerfish",
    "Mood Lantern",
    "Moral Less",
    "More4Less",
    "Moreganic",
    "Mr. Fortnight",
    "Mr. Frenzy",
    "Mr. Interiors",
    "Mr. Mercurial",
    "Mrs. Clean",
    "Mrs. Deacon Jones",
    "Mrs. Richard Ramirez",
    "Ms. Alliance",
    "Ms. Beehaven",
    "Ms. Demeanor",
    "Ms. Dialed",
    "Ms. Ducky",
    "Ms. Excellency",
    "Ms. Marx",
    "mY pHi XiLO",
    "N. Oprah",
    "Nabokov Drops",
    "Nadaville",
    "Nagpie",
    "Naïveté",
    "Namby Pam B.",
    "Narrow Barrow",
    "Naughty Towers",
    "Never B-R8 the B8",
    "Newly Wedlock",
    "Notorious",
    "Nylon Prawn",
    "O Jackie",
    "O8 is Bettor",
    "Obones",
    "Obscene Serene",
    "Occasion Alice",
    "Occasion Olly",
    "Occupassion",
    "Octorex",
    "Off8",
    "Oma Hasbeen",
    "OmaHa Hum",
    "Omahannibal",
    "Omahans",
    "Omahanz",
    "Omahate",
    "Omahaughty",
    "Omahonk",
    "Omahonky",
    "Omahotty",
    "Omahunk",
    "Omatom",
    "Omnipotaunt",
    "On High",
    "Oscillation",
    "Overchurros",
    "Pa Kafka",
    "Pablo Pick Ax O",
    "Pabst",
    "Pan Ash",
    "Panache",
    "Papricut",
    "Paprikash",
    "Paranoma",
    "Pariah Carey",
    "Parish Able",
    "ParNayVous",
    "Partial Toast",
    "Parvenu Barbie",
    "Parvenu Charlie",
    "Parvenu Guru",
    "Parvenu Porkchop",
    "Patch Puffing",
    "Patchwork Guilt",
    "Patchwork Kilt",
    "Patty Meal",
    "Patty Meltdown",
    "Patty Prawn",
    "Paul Tree",
    "Paul Treesum",
    "Pawn Bons",
    "Pawn Pawn",
    "Pawn Queen",
    "Pawn Storm",
    "Pawn Tiff",
    "Pawntiff",
    "Paws for Thought",
    "Pearlesex",
    "Peerless Dulcinea",
    "Pelé Monty",
    "Penultimate Cute",
    "Pepperboard",
    "Pessifist",
    "Pheast",
    "Pheast West",
    "Pheno Barbie Doll",
    "Pheromona",
    "Pheromona Lisa",
    "Pheromone Jones",
    "Pheromonia",
    "Pier Deer",
    "Piss Intellect",
    "Pisserd",
    "Pit Poodle",
    "Pittsburg Rush",
    "Plaid Certain",
    "Planet Harry",
    "Planet Plaid",
    "Planet Terry",
    "Plank 10",
    "Plasto",
    "Pocket Q’s Brooklyn",
    "Pomme Juan",
    "Pomona Lisa",
    "Pompiex",
    "Pop Cycle",
    "Pop Gunz",
    "Popcorn Born",
    "Popcorn Logic",
    "Popcorn Pauper",
    "Popo",
    "Poppydom",
    "Pop-up Buddha",
    "Prawn God",
    "Prawn to Own",
    "Princess Plex",
    "Probiscus",
    "Puck U",
    "Puff Chuck",
    "Pumpty Dumpty",
    "Puncake",
    "Punkies",
    "Pure Penguin",
    "Purple Letters",
    "Puttylax",
    "Qiao",
    "Qimonk",
    "Qleen",
    "Qoolqi",
    "Qot",
    "Quadeebo",
    "Quadzoonple",
    "Quaff Drops",
    "Quake Dance",
    "Quakerdope",
    "Qualm Temptress",
    "Quantum Taco",
    "Quappi",
    "Quarkie",
    "Quatre-Vingts Morrison",
    "Que Papa",
    "Que West",
    "Queen Beam",
    "Queen Conundrum",
    "Queen Martyr",
    "Queen of Hype",
    "Quella",
    "Quimby Heights",
    "Rabbit Lounge",
    "Rabid Rabbit",
    "Raccoon Tour",
    "Radamus",
    "Radiant Butane",
    "Radiant Ease",
    "Radiant Fresh",
    "Radiant Swift",
    "Radiccious",
    "Radio Certainty",
    "Radio My",
    "Radioblade",
    "Radiopaste",
    "RADr",
    "Random Excellence",
    "Rap Doodle",
    "Rate the B8",
    "Razz Barney",
    "Razzbo",
    "Razzing Cane",
    "Realm of the Woods",
    "Reform Torn",
    "Reno Boy",
    "Repo Mantis",
    "Retro",
    "Reward Chord",
    "Rin Tin Thin",
    "Ring Bling",
    "Ritual Wave",
    "Rocket Red",
    "Rodent Scholar",
    "Rodeo Jones",
    "Rodeo Oracle",
    "Rodeo Warp",
    "RodeoStorm",
    "Ronbert",
    "Royal Lush",
    "Royal Plush",
    "Royal Tease",
    "Rudyard Quizling",
    "Rumor Goddess",
    "Rutabaga Darling",
    "Rutabaga Princess",
    "Ruthless Toothless",
    "S.T. Dingleberry",
    "Saab Story",
    "Saber Kath",
    "Sabre Slayers",
    "Sacred Cowboy",
    "Sadie Blue",
    "Saffronia",
    "Salmon Ella",
    "Salon Da Bomb",
    "Salvy",
    "Samopolis",
    "Sanchica de Ville",
    "Sanctummy",
    "Sand Flower",
    "Sans Charo",
    "Saphire Rose",
    "Saphron Sunrise",
    "Sar Donna",
    "Sar Donovan",
    "Sara Bellum",
    "Sara Soda",
    "Sara Vellum",
    "Sarah Tonin’",
    "Saskatchewonder",
    "Sassybox",
    "Save the Ants",
    "Sceen Seen",
    "Scene Beam",
    "Scene Not Herd",
    "Schplasm",
    "Screaming Tuesday",
    "Sea Quimby",
    "Sea Quinn",
    "Sea Script",
    "Sea Sleigh",
    "Sea Spam",
    "Sea Tan",
    "Sea Windsor",
    "Selective Depression",
    "Señor Circumstance",
    "Señor Serene",
    "Sequin",
    "Serpent Stance",
    "Shape the Scape",
    "Sharkspot",
    "Shelly Half",
    "Sherman Opus",
    "Shock and Almonds",
    "Sidewalk Crack",
    "Sigh Bore",
    "Sigh Bore Space",
    "Sigh Clone",
    "Sigh Co.",
    "Sigh Girl",
    "Sigh Guy",
    "SiGH wReen",
    "Simon Rusty",
    "Simply Gorge Us",
    "Sin Drone",
    "Sin n’ Spin",
    "Sin Sin",
    "Sin Thesis",
    "Sindrome",
    "Sindromo",
    "Sing Bling",
    "Singavera",
    "Sir Donna",
    "Sir Drone",
    "Sir Elton",
    "Sir Flotsam",
    "Sir Jetsam",
    "Sir Miser",
    "Sir Nuthead",
    "Sir Raw",
    "Sir Render",
    "Sir Zen",
    "Sister Borneo",
    "Sister Griswald",
    "Sister Resister",
    "Sister Resistor",
    "Sisterine",
    "Skin Bin",
    "Skin Deeper",
    "Skinny Boboli",
    "Slackered",
    "Smarty Jonestown",
    "Snub Hall",
    "Sonata Fast",
    "Songbird",
    "Sorb",
    "Spacewax",
    "Spam Bucket",
    "Spam Goodys",
    "Spamo",
    "Spare a Digm",
    "Spavin",
    "Spawn Chalant",
    "Spawn Shawn",
    "Speedbolt",
    "sPlasTiC",
    "sPLeeN siReNe",
    "Sproil",
    "Stage Wrong",
    "Stampled",
    "Stavrogin",
    "STD Superstore",
    "STD Warehouse",
    "Steam Beat",
    "Str8 at Ya",
    "Str8 Flush’d",
    "Str8 Jacket",
    "Str8 UPp",
    "Str8-10 uPp",
    "Str8en uPp",
    "Sugar Doggy",
    "Sun Bite",
    "Sunbit",
    "Sunbright Sparrow",
    "Sunbright Swallow",
    "Super Ciao",
    "Super Cize",
    "Super Nothing",
    "Svelt Smelt",
    "Swim Beam",
    "Swing Bing",
    "Swing Bling",
    "sWWEEETie",
    "Tab Bandit",
    "Taco Belfast",
    "Taco Boil",
    "Tae Bozo",
    "Tai Chi Toes",
    "Teazy Pleasey",
    "Tele Vangelis",
    "Texas Firewalker",
    "Texass",
    "Texx",
    "Thai Cheetos",
    "Thar Hills",
    "The Adhoc",
    "The Bali Who",
    "The Bane",
    "The Barkley",
    "The Big One",
    "The Blockloc",
    "The Bovine",
    "The Brime",
    "The BumpKin",
    "The Captainstance",
    "The Chute",
    "The Contessa",
    "The Crustacean",
    "The Deuce",
    "The Dollop",
    "The Dreamery",
    "The Duke",
    "The Element",
    "The Flight",
    "The Flotsam",
    "The Gipper",
    "The Glean",
    "The Gleen",
    "The Gluck",
    "The Go Lucky",
    "The Good Nothin’s",
    "The Jones",
    "The Knotch",
    "The Lollytart",
    "The Monte Magum",
    "The Panky",
    "The Plutarch",
    "The Portion",
    "The Prudence",
    "The Randy",
    "The Ripper",
    "The Sanguine",
    "The Secretarian",
    "The Sedge",
    "The Snark",
    "The Snub",
    "The Snunt",
    "The Spirit",
    "The Stavrogin",
    "The Stool Pigeon",
    "The Stranger",
    "The Swift",
    "The Tawd",
    "The Throwback",
    "The TiM Shaq",
    "The Torquemada",
    "The Turn",
    "The Wanta Be",
    "The Wedge",
    "The Wellborne",
    "The Whoopie",
    "tHeMatic",
    "Tone Bone",
    "Tongue in Chic",
    "Tony Mutton",
    "Torpor Ritz",
    "Torpor Royale",
    "Torpor Senate",
    "Toy Botox",
    "Tran Annie",
    "Tranny Hall",
    "Trips not Trips",
    "Trips’n",
    "Trope Scope",
    "Trophyplex",
    "Trouble Bubble",
    "True By You",
    "True Fo",
    "True Foe",
    "Turnling",
    "Tweezy",
    "Twiggery",
    "Twiist",
    "Tyro Scene",
    "Uber Geek",
    "Uber Goober",
    "Uberlux",
    "UberPrawn",
    "Ughly",
    "Uh Oh-Bama",
    "Ukranian Sister",
    "Ultra Mouse",
    "Ultramouse",
    "Ultrasure",
    "Umpa Lava",
    "Uncle Billychord",
    "Uncle Boredom",
    "Uncle Bulgaria",
    "Uncle Goldilocks",
    "Uncle Thunder",
    "Under Thunder",
    "Underbelly",
    "Uni",
    "Unq",
    "Up Chucky!",
    "Upper Dinero",
    "Upperimage",
    "UpsZcale",
    "UpXOR",
    "uPzKaLE",
    "Urbanshee",
    "URLy",
    "Urugly",
    "User Friend Lee",
    "Uxmox",
    "Uzi Q",
    "Vacant Lot",
    "Vacua",
    "Vaginasaurus",
    "Vagraunt",
    "Valet Dictorian",
    "Valmyra",
    "Veggiegasm",
    "Veil Crow",
    "Veltiphid",
    "Velvet Thorax",
    "Venetian Sack",
    "Very Old Crow",
    "Waab",
    "Waffle Stomper",
    "Waisting Away",
    "Walla Wild",
    "Wannabe Grand",
    "Wannabe Heights",
    "Wasteband",
    "Weeeeeeeee",
    "Weeeeeeeeeee",
    "Welchommie",
    "Wicked Cute",
    "Wicker Dicker",
    "Wig It!",
    "Wigworm",
    "Wreck Lass",
    "X Flip",
    "X Kitty",
    "Xanide",
    "Xbones",
    "Xcreta",
    "Xeno Clip",
    "Xerex",
    "xiixL",
    "Xixan",
    "Xleen",
    "XOR More",
    "XOR Tracks",
    "XORAID",
    "XORCat",
    "Xorette",
    "Xorling",
    "XORspawn",
    "XORts",
    "Xplor",
    "XtasTIC",
    "XtasTIC pLAStic",
    "Xth",
    "Xumonk",
    "Xylar",
    "Xyqag",
    "Xytrexin",
    "Y Tokyo",
    "Y2 Kiki",
    "Y2Canine",
    "Y2Chaos",
    "Yankee Ass",
    "Yester Yore",
    "YipYaw",
    "Yo Phat!",
    "Yo Yo Tokyo",
    "Yo Yorkshire",
    "Yogasm",
    "Yore Store",
    "YoYo Go",
    "Yugo Not!",
    "Yumber",
    "Zachary All",
    "Zaggle",
    "Zaggles",
    "Zamora",
    "Zap Shack",
    "Zazz",
    "Zboo",
    "Zeam",
    "Zelluloid",
    "Zelpo",
    "Zen Cohen",
    "Zenacity",
    "Zenka",
    "Zentrapore",
    "Zerbina",
    "ZeusNoose",
    "Ziggy Endust",
    "Zilla Drop",
    "Zillabells",
    "Zillaberry",
    "Zillabug",
    "Zillanoid",
    "Zinch",
    "Zinful",
    "Zizzle",
    "Zizzy",
    "Zizzy Blue",
    "Zog",
    "Zogak",
    "Zombie Logic",
    "Zoospore",
    "Zoot A. Larz",
    "Zophie",
    "Zorax",
    "Zork",
    "Zorromop",
    "Zoxy",
    "Zubin Jeffries",
    "Zukalu",
    "Zuke",
    "Zuniper",
    "Zutros",
    "Zuvy",
    "Zwebby",
    "Zyple"
  ];
  const bios = [
    "velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac",
    "Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a,",
    "malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id",
    "justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec",
    "non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,",
    "urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et",
    "justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras",
    "amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in",
    "mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,",
    "Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat",
    "eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris",
    "Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac",
    "sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut",
    "arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,",
    "ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat,",
    "sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a",
    "odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum",
    "Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien.",
    "Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus,",
    "ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non",
    "egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper",
    "magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque",
    "nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed",
    "risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris",
    "placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis.",
    "pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,",
    "neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh",
    "nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede",
    "eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante.",
    "nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem",
    "placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna",
    "placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent",
    "Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac,",
    "a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam,",
    "luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio",
    "mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy",
    "nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed",
    "lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in",
    "est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce",
    "elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui",
    "a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante",
    "dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum",
    "dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
    "nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,",
    "dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh",
    "hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio,",
    "massa non ante bibendum ullamcorper. Duis cursus, diam at pretium",
    "velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere",
    "arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer",
    "ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed",
    "egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est",
    "orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu",
    "vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis",
    "et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum",
    "nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus,",
    "arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.",
    "eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam",
    "nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia",
    "dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna.",
    "in sodales elit erat vitae risus. Duis a mi fringilla",
    "malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim",
    "orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero",
    "aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui",
    "amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.",
    "Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut",
    "condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt.",
    "aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis",
    "et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,",
    "dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum",
    "hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",
    "enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero",
    "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.",
    "sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",
    "Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non",
    "eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales",
    "Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,",
    "Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris",
    "auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.",
    "consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante",
    "erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque",
    "rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi.",
    "Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula",
    "placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",
    "faucibus leo, in lobortis tellus justo sit amet nulla. Donec non",
    "lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa.",
    "rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac",
    "Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl",
    "eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",
    "Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede",
    "in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac",
    "lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin",
    "egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus",
    "nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet",
    "urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam",
    "sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque",
    "Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui.",
    "Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu",
    "ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida",
    "eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo"
  ];
  const tags = [
    "Mauris",
    "semper",
    "mollis",
    "Quisque",
    "sapien.",
    "Mauris",
    "penatibus",
    "Mauris",
    "Aliquam",
    "ridiculus",
    "pellentesque,",
    "at",
    "Nulla",
    "vel",
    "egestas.",
    "eget",
    "Nulla",
    "massa.",
    "ultrices,",
    "Praesent",
    "feugiat",
    "aliquam,",
    "nec,",
    "lectus",
    "volutpat.",
    "faucibus.",
    "arcu.",
    "in",
    "nec",
    "mi,",
    "ultrices.",
    "Fusce",
    "arcu.",
    "consectetuer",
    "risus.",
    "dictum",
    "lectus,",
    "varius",
    "placerat,",
    "sociosqu",
    "Proin",
    "augue",
    "vehicula",
    "risus.",
    "euismod",
    "ornare,",
    "Vestibulum",
    "nec,",
    "amet",
    "Cum",
    "ultricies",
    "tristique",
    "Praesent",
    "nibh",
    "lobortis",
    "blandit",
    "lobortis",
    "tincidunt",
    "ut",
    "mi",
    "a",
    "facilisis,",
    "Aliquam",
    "ac",
    "semper",
    "rutrum",
    "tellus",
    "iaculis,",
    "magna.",
    "ut,",
    "scelerisque,",
    "turpis",
    "arcu",
    "et",
    "dui.",
    "nulla",
    "amet,",
    "malesuada",
    "magnis",
    "vel",
    "Pellentesque",
    "Proin",
    "purus,",
    "amet",
    "sed,",
    "dapibus",
    "posuere",
    "Morbi",
    "natoque",
    "ullamcorper",
    "libero",
    "velit",
    "vehicula.",
    "euismod",
    "eget",
    "arcu",
    "primis",
    "feugiat",
    "orci,",
    "adipiscing"
  ];
  const urls = [
    "https://pbs.twimg.com/media/CnrFVXqW8AA4TO_.jpg",
    "https://farm8.staticflickr.com/7426/12233323463_2fe29374ce_c.jpg",
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT2DoRmP6QnHJahLazzRAUzDQkCIe3QpbTDLIECSrw03dyGHndK",
    "https://c7.staticflickr.com/2/1480/24038441374_b51735c601_f.jpg",
    "https://farm4.staticflickr.com/3917/14646855999_d59e5ce9c5_c.jpg",
    "https://c1.staticflickr.com/2/1489/25373592304_a6e3054a4c_b.jpg",
    "https://farm1.staticflickr.com/591/22665222766_244f36dfc0_c.jpg",
    "https://c6.staticflickr.com/6/5640/23693430901_4045fa2c73_b.jpg",
    "https://c1.staticflickr.com/1/54/177633687_4e37d80aa0_b.jpg",
    "https://c2.staticflickr.com/2/1519/24649255286_03bb5ab0e3_b.jpg",
    "https://farm1.staticflickr.com/661/21230969582_5c642e4b0e_c.jpg",
    "https://c1.staticflickr.com/2/1534/24322384224_e878fc6b77_b.jpg",
    "https://c1.staticflickr.com/3/2906/14616245588_f3be141409_b.jpg",
    "https://c1.staticflickr.com/9/8047/8437821167_ab25401d98_b.jpg",
    "http://petapixel.com/assets/uploads/2013/07/full360.jpg",
    "https://c6.staticflickr.com/3/2936/14749427013_c8fdbc4c76_z.jpg",
    "https://rawgit.com/aframevr/assets/gh-pages/360-image-gallery-boilerplate/img/sechelt.jpg"
  ];
  const texts = [
    "sem",
    "eget, volutpat",
    "Cras vehicula aliquet",
    "aliquet",
    "mauris sapien, cursus",
    "ipsum",
    "velit. Sed malesuada",
    "Sed",
    "scelerisque dui. Suspendisse",
    "Cras",
    "dapibus id,",
    "cursus purus.",
    "lorem, auctor",
    "mauris eu",
    "suscipit, est ac",
    "tellus",
    "Curabitur dictum. Phasellus",
    "felis purus ac",
    "montes, nascetur",
    "Cras convallis",
    "risus quis diam",
    "Maecenas mi",
    "vitae aliquam",
    "vulputate",
    "mauris",
    "ipsum non",
    "scelerisque dui.",
    "Donec est",
    "ut, sem.",
    "Aenean",
    "Etiam",
    "tincidunt, neque vitae",
    "fringilla",
    "nunc,",
    "ac",
    "et",
    "tortor. Integer",
    "sapien. Cras dolor",
    "lobortis quis, pede.",
    "nunc",
    "adipiscing non,",
    "a,",
    "nec",
    "sem ut dolor",
    "velit. Cras lorem",
    "nulla. Integer",
    "ultrices",
    "Vivamus euismod",
    "risus, at fringilla",
    "sit amet, consectetuer",
    "amet, consectetuer adipiscing",
    "rutrum",
    "aliquam arcu. Aliquam",
    "consectetuer adipiscing elit.",
    "et,",
    "neque",
    "magna sed",
    "ac mattis",
    "tristique aliquet. Phasellus",
    "ac,",
    "ligula. Nullam enim.",
    "nisl.",
    "Cras",
    "aliquet",
    "vitae, sodales at,",
    "vitae dolor.",
    "eu arcu.",
    "lacus.",
    "vel,",
    "vel",
    "convallis, ante lectus",
    "vitae, aliquet",
    "auctor odio",
    "Cras",
    "leo. Morbi",
    "a",
    "Quisque",
    "faucibus.",
    "amet lorem semper",
    "a, facilisis",
    "consequat enim diam",
    "penatibus et magnis",
    "bibendum. Donec felis",
    "ante. Vivamus non",
    "amet,",
    "leo, in",
    "sed sem egestas",
    "metus. Aliquam erat",
    "amet massa.",
    "lorem, sit",
    "odio.",
    "eget",
    "enim. Nunc ut",
    "Quisque",
    "lectus, a sollicitudin",
    "augue eu tellus.",
    "hendrerit",
    "sem molestie",
    "ullamcorper.",
    "magna. Suspendisse tristique"
  ];
  const colors = [
    "#BEBD7F",
    "#C2B078",
    "#C6A664",
    "#E5BE01",
    "#CDA434",
    "#A98307",
    "#E4A010",
    "#DC9D00",
    "#8A6642",
    "#C7B446",
    "#EAE6CA",
    "#E1CC4F",
    "#E6D690",
    "#EDFF21",
    "#F5D033",
    "#F8F32B",
    "#9E9764",
    "#999950",
    "#F3DA0B",
    "#FAD201",
    "#AEA04B",
    "#FFFF00",
    "#9D9101",
    "#F4A900",
    "#D6AE01",
    "#F3A505",
    "#EFA94A",
    "#6A5D4D",
    "#705335",
    "#F39F18",
    "#ED760E",
    "#C93C20",
    "#CB2821",
    "#FF7514",
    "#F44611",
    "#FF2301",
    "#FFA420",
    "#F75E25",
    "#F54021",
    "#D84B20",
    "#EC7C26",
    "#E55137",
    "#C35831",
    "#AF2B1E",
    "#A52019",
    "#A2231D",
    "#9B111E",
    "#75151E",
    "#5E2129",
    "#412227",
    "#642424",
    "#781F19",
    "#C1876B",
    "#A12312",
    "#D36E70",
    "#EA899A",
    "#B32821",
    "#E63244",
    "#D53032",
    "#CC0605",
    "#D95030",
    "#F80000",
    "#FE0000",
    "#C51D34",
    "#CB3234",
    "#B32428",
    "#721422",
    "#B44C43",
    "#6D3F5B",
    "#922B3E",
    "#DE4C8A",
    "#641C34",
    "#6C4675",
    "#A03472",
    "#4A192C",
    "#924E7D",
    "#A18594",
    "#CF3476",
    "#8673A1",
    "#6C6874",
    "#354D73",
    "#1F3438",
    "#20214F",
    "#1D1E33",
    "#18171C",
    "#1E2460",
    "#3E5F8A",
    "#26252D",
    "#025669",
    "#0E294B",
    "#231A24",
    "#3B83BD",
    "#1E213D",
    "#606E8C",
    "#2271B3",
    "#063971",
    "#3F888F",
    "#1B5583",
    "#1D334A",
    "#256D7B",
    "#252850",
    "#49678D",
    "#5D9B9B",
    "#2A6478",
    "#102C54",
    "#316650",
    "#287233",
    "#2D572C",
    "#424632",
    "#1F3A3D",
    "#2F4538",
    "#3E3B32",
    "#343B29",
    "#39352A",
    "#31372B",
    "#35682D",
    "#587246",
    "#343E40",
    "#6C7156",
    "#47402E",
    "#3B3C36",
    "#1E5945",
    "#4C9141",
    "#57A639",
    "#BDECB6",
    "#2E3A23",
    "#89AC76",
    "#25221B",
    "#308446",
    "#3D642D",
    "#015D52",
    "#84C3BE",
    "#2C5545",
    "#20603D",
    "#317F43",
    "#497E76",
    "#7FB5B5",
    "#1C542D",
    "#193737",
    "#008F39",
    "#00BB2D",
    "#78858B",
    "#8A9597",
    "#7E7B52",
    "#6C7059",
    "#969992",
    "#646B63",
    "#6D6552",
    "#6A5F31",
    "#4D5645",
    "#4C514A",
    "#434B4D",
    "#4E5754",
    "#464531",
    "#434750",
    "#293133",
    "#23282B",
    "#332F2C",
    "#686C5E",
    "#474A51",
    "#2F353B",
    "#8B8C7A",
    "#474B4E",
    "#B8B799",
    "#7D8471",
    "#8F8B66",
    "#D7D7D7",
    "#7F7679",
    "#7D7F7D",
    "#B5B8B1",
    "#6C6960",
    "#9DA1AA",
    "#8D948D",
    "#4E5452",
    "#CAC4B0",
    "#909090",
    "#82898F",
    "#D0D0D0",
    "#898176",
    "#826C34",
    "#955F20",
    "#6C3B2A",
    "#734222",
    "#8E402A",
    "#59351F",
    "#6F4F28",
    "#5B3A29",
    "#592321",
    "#382C1E",
    "#633A34",
    "#4C2F27",
    "#45322E",
    "#403A3A",
    "#212121",
    "#A65E2E",
    "#79553D",
    "#755C48",
    "#4E3B31",
    "#763C28",
    "#FDF4E3",
    "#E7EBDA",
    "#F4F4F4",
    "#282828",
    "#0A0A0A",
    "#A5A5A5",
    "#8F8F8F",
    "#FFFFFF",
    "#1C1C1C",
    "#F6F6F6",
    "#1E1E1E",
    "#D7D7D7",
    "#9C9C9C",
    "#828282",
  ];
  const descriptions = [
    "odio tristique pharetra. Quisque ac",
    "tellus. Suspendisse sed dolor. Fusce mi lorem,",
    "pede, nonummy ut, molestie in, tempus",
    "est arcu ac orci. Ut semper pretium neque.",
    "eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci",
    "et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus",
    "eget nisi dictum augue malesuada malesuada.",
    "venenatis vel, faucibus id, libero. Donec consectetuer",
    "libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus",
    "scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris",
    "sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum",
    "ornare lectus justo eu arcu. Morbi sit amet",
    "est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque",
    "eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin",
    "dictum augue malesuada malesuada. Integer id magna et ipsum",
    "lorem ipsum sodales purus, in",
    "Aenean egestas hendrerit neque. In",
    "malesuada id, erat. Etiam vestibulum massa rutrum",
    "Integer tincidunt aliquam arcu. Aliquam ultrices iaculis",
    "Mauris ut quam vel sapien imperdiet ornare. In faucibus.",
    "risus varius orci, in consequat",
    "Donec consectetuer mauris id sapien. Cras dolor dolor, tempus",
    "ut, sem. Nulla interdum. Curabitur dictum.",
    "Etiam ligula tortor, dictum eu, placerat",
    "sodales purus, in molestie tortor nibh sit amet orci. Ut",
    "interdum ligula eu enim. Etiam",
    "parturient montes, nascetur ridiculus mus. Proin vel",
    "volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla",
    "lectus convallis est, vitae sodales nisi",
    "luctus aliquet odio. Etiam ligula",
    "a, auctor non, feugiat nec, diam. Duis mi enim,",
    "aliquet odio. Etiam ligula tortor, dictum",
    "varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla",
    "augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna",
    "arcu. Sed et libero. Proin mi. Aliquam gravida mauris",
    "ut lacus. Nulla tincidunt, neque vitae semper egestas,",
    "imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt",
    "Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
    "mauris id sapien. Cras dolor dolor, tempus non, lacinia",
    "et malesuada fames ac turpis egestas. Aliquam fringilla cursus",
    "Fusce mollis. Duis sit amet diam eu",
    "sapien, gravida non, sollicitudin a, malesuada id,",
    "arcu et pede. Nunc sed",
    "pede ac urna. Ut tincidunt vehicula",
    "tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi.",
    "nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse",
    "magna, malesuada vel, convallis in, cursus et, eros.",
    "eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed",
    "felis, adipiscing fringilla, porttitor vulputate, posuere",
    "cursus a, enim. Suspendisse aliquet, sem ut cursus",
    "gravida sit amet, dapibus id, blandit at, nisi. Cum sociis",
    "sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam",
    "pede. Cras vulputate velit eu sem. Pellentesque ut ipsum",
    "ultricies dignissim lacus. Aliquam rutrum",
    "dolor. Quisque tincidunt pede ac urna. Ut tincidunt",
    "Maecenas mi felis, adipiscing fringilla,",
    "mauris ipsum porta elit, a feugiat tellus",
    "Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet",
    "risus. Donec nibh enim, gravida sit amet, dapibus",
    "metus eu erat semper rutrum. Fusce",
    "a felis ullamcorper viverra. Maecenas iaculis aliquet",
    "pede. Cum sociis natoque penatibus et magnis dis parturient montes,",
    "Fusce diam nunc, ullamcorper eu, euismod ac,",
    "in aliquet lobortis, nisi nibh lacinia",
    "nibh. Aliquam ornare, libero at auctor ullamcorper, nisl",
    "erat. Etiam vestibulum massa rutrum magna. Cras convallis",
    "tempor bibendum. Donec felis orci, adipiscing",
    "feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum",
    "Mauris magna. Duis dignissim tempor arcu. Vestibulum ut",
    "rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,",
    "Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus",
    "Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus.",
    "et malesuada fames ac turpis egestas. Aliquam fringilla",
    "molestie. Sed id risus quis diam",
    "lacinia. Sed congue, elit sed consequat auctor, nunc",
    "porttitor tellus non magna. Nam ligula elit, pretium et, rutrum",
    "mauris, rhoncus id, mollis nec, cursus",
    "libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit",
    "Cum sociis natoque penatibus et magnis",
    "nisi. Aenean eget metus. In",
    "elementum sem, vitae aliquam eros turpis",
    "Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a,",
    "Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.",
    "sed, facilisis vitae, orci. Phasellus dapibus quam quis diam.",
    "dui, semper et, lacinia vitae, sodales at, velit.",
    "nunc. In at pede. Cras vulputate velit eu sem. Pellentesque",
    "primis in faucibus orci luctus",
    "non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget",
    "non, dapibus rutrum, justo. Praesent luctus.",
    "tempor erat neque non quam. Pellentesque",
    "malesuada malesuada. Integer id magna et ipsum",
    "est. Mauris eu turpis. Nulla aliquet. Proin velit.",
    "sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris",
    "diam dictum sapien. Aenean massa. Integer",
    "erat semper rutrum. Fusce dolor quam,",
    "amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum",
    "tincidunt. Donec vitae erat vel pede blandit",
    "ipsum leo elementum sem, vitae aliquam eros turpis non",
    "sed pede nec ante blandit",
    "semper pretium neque. Morbi quis urna."
  ];
  const emoji = [
    'Smiley-Face',
    'Frowny-Face',
    'Poopy-Face',
    'Lolz-Face',
    'Heart-Face',
    'Whoah-Face'
  ];

  const numUsers = 20;
  const minFollows = 2;
  const maxFollows = 10;
  const minUserTags = 3;
  const maxUserTags = 7;
  const minPosts = 2;
  const maxPosts = 5;
  const minPostTags = 1;
  const maxPostTags = 5;
  const minResponses = 2;
  const maxResponses = 5;

  let sqlString = "\n"+
                  "USE glimpse;\n"+
                  "DELETE FROM emoji;\n"+
                  "ALTER TABLE emoji AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM follow;\n"+
                  "ALTER TABLE follow AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM notification;\n"+
                  "ALTER TABLE notification AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM post;\n"+
                  "ALTER TABLE post AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM post_tags;\n"+
                  "ALTER TABLE post_tags AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM tag;\n"+
                  "ALTER TABLE tag AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM user;\n"+
                  "ALTER TABLE user AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM user_emoji_post;\n"+
                  "ALTER TABLE user_emoji_post AUTO_INCREMENT = 1;\n"+
                  "DELETE FROM user_tags;\n"+
                  "ALTER TABLE user_tags AUTO_INCREMENT = 1;\n"

  let username = '';
  let profpic = '';
  let authId = '';
  let email = '';
  let bio = '';
  let dob = '';
  let gender = '';
  let private = 0;
  let createdAt = '';

  for (let i=1; i <= numUsers; i++) {
    username = usernames[Math.floor(Math.random()*usernames.length)]
    gender = Math.random() > 0.5 ? 'men' : 'women';
    profpic = 'https://randomuser.me/api/portraits/med/'+gender+'/'+Math.floor(Math.random()*100)+'.jpg';
    authId = 'dummy|'+i;
    email = 'GlimpseTest'+i+'@mailinator.com';
    bio = bios[Math.floor(Math.random()*bios.length)];
    dob = Math.floor(Math.random()*40)+1970+'-0'+Math.floor(1+Math.random()*8.9)+'-'+Math.floor(Math.random()*18+10);
    private = Math.random() < 0.75 ? 0 : 1;
    createdAt = '2016-10-'+Math.floor(10+Math.random()*21)+' 11:11:11';

    sqlString += "INSERT into `user` "+
                 "(`username`, `profpic`, `authId`,`email`,`bio`,`dob`,"+
                 "`gender`,`private`,`createdAt`,`updatedAt`)\n"+
                 "VALUES('"+username+"','"+profpic+"','"+authId+"','"+email+"',\n'"+bio+
                 "',\n'"+dob+"','"+gender+"',"+private+",'"+createdAt+"','"+createdAt+"');\n"
  }
  sqlString += '\n';

  let numFollows = minFollows;
  let status= '';
  let userId = 0
  let followId = 0;

  for (let i=1; i <= numUsers; i++) {
    let usedFollows = {};
    userId = i;
    numFollows = minFollows + Math.floor(Math.random()*(maxFollows-minFollows))
    for (let j = 0; j < numFollows; j++) {
      status = Math.random() < 0.75 ? "accepted" : "pending";
      followId = Math.ceil(Math.random()*numUsers)
      while (followId === userId || usedFollows[followId]) {
        followId = Math.ceil(Math.random()*numUsers)
      }
      usedFollows[followId] = true;
      sqlString += "INSERT into `follow` (`status`, `createdAt`,`updatedAt`,`UserId`,`FollowId`)"+
                   " VALUES('"+status+"', NOW(), NOW(), "+userId+", "+followId+");\n"
    }
  }
  sqlString += '\n';

  for (let i = 0; i < tags.length; i++) {
    sqlString += "INSERT into `tag` (`name`,`createdAt`,`updatedAt`)"+
                 " VALUES('"+tags[i]+"', NOW(), NOW());\n"
  }
  sqlString += '\n';

  let numUserTags = minUserTags;
  let tag = '';

  for (let i=1; i <= numUsers; i++) {
    let usedTags = {};
    numUserTags = minUserTags + Math.floor(Math.random()*(maxUserTags-minUserTags))
    for (let j = 0; j < numUserTags; j++) {
      tagId = Math.ceil(Math.random()*tags.length);
      while (usedTags[tagId]) {
        tagId = Math.ceil(Math.random()*tags.length);
      }
      usedTags[tagId] = true;
      sqlString += "INSERT into `user_tags` (`createdAt`,`updatedAt`,`UserId`,`TagId`)"+
                   " VALUES(NOW(), NOW(), "+i+", "+tagId+");\n"
    }
  }
  sqlString += '\n';

  let numPosts = minPosts;
  let content = '';
  let description = '';
  let format = 'PhotoSphere';
  let totalPosts = 0;

  for (let i=1; i <= numUsers; i++) {
    userId = i;
    numPosts = minPosts + Math.floor(Math.random()*(maxPosts-minPosts));
    for (let j = 0; j < numPosts; j++) {
      content = '[{"primitive":"PhotoSphere","components":{"src":'+
                '"url('+urls[Math.floor(Math.random()*urls.length)]+
                ')"},"children":null},{"primitive":"Text","components":'+
                '{"text":"'+texts[Math.floor(Math.random()*texts.length)]+
                '","color":"'+colors[Math.floor(Math.random()*colors.length)]+
                '","position":"-1.75 1 -3"}}]';
      description = descriptions[Math.floor(Math.random()*descriptions.length)];
      private = Math.random() < 0.8 ? 0 : 1;
      createdAt = '2016-'+Math.floor(11+Math.random()*2-.1)+'-'+Math.floor(10+Math.random()*20)+' 11:11:11';
      sqlString += "INSERT into `post` (`content`,`description`,`format`,"+
                   "`private`,`createdAt`,`updatedAt`,`UserId`)\n"+
                   "VALUES('"+content+"',\n"+"'"+description+"',\n'"+format+
                   "', "+private+", '"+createdAt+"','"+createdAt+"', "+userId+");\n";
      totalPosts++
    }
  }
  sqlString += '\n';

  let numPostTags = minPostTags;
  let postId = 0

  for (let i=1; i <= totalPosts; i++) {
    let usedTags = {};
    postId = i;
    numPostTags = minPostTags + Math.floor(Math.random()*(maxPostTags-minPostTags));
    for (let j=0; j < numPostTags; j++) {
      tagId = Math.ceil(Math.random()*tags.length);
      while (usedTags[tagId]) {
        tagId = Math.ceil(Math.random()*tags.length);
      }
      usedTags[tagId] = true;
      sqlString += "INSERT into `post_tags` (`createdAt`,`updatedAt`,`TagId`,`PostId`)"+
                   " VALUES(NOW(), NOW(), "+tagId+", "+postId+");\n"
    }
  }
  sqlString += '\n';

  let emojiId = 0;
  for (let i = 0; i < emoji.length; i++){
    emojiId = i;
    sqlString += "INSERT into `emoji` (`name`,`json`,`createdAt`,`updatedAt`)"+
                 " VALUES('"+emojiId+"','json-string',NOW(),NOW());\n"
  }
  sqlString += '\n';

  let numResponses = minResponses;

  for (let i=1; i <= totalPosts; i++) {
    let usedUsers = {};
    postId=i;
    numResponses = minResponses + Math.floor(Math.random()*(maxResponses-minResponses));
    for (let j = 0; j < numResponses; j++) {
      emojiId = Math.ceil(Math.random()*emoji.length);
      userId = Math.ceil(Math.random()*numUsers);
      while (usedUsers[userId]) {
        userId = Math.ceil(Math.random()*numUsers);
      }
      usedUsers[userId] = true;
      sqlString += "INSERT into `user_emoji_post` (`createdAt`,`updatedAt`,`EmojiId`,`PostId`,`UserId`)"+
                   " VALUES (NOW(), NOW(), "+emojiId+", "+postId+", "+userId+");\n"
    }
  }
  sqlString += '\n';

  console.log(sqlString);
}